version: '3.1'
services:
  datasource:
    restart: always
    build:
      context: ../..
      dockerfile: ./docker/server/Dockerfile
    ports:
      - "8080:8080"
    container_name: chatr
    image: chatr/server
